version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.4

references:

deploy_base_image: &deploy_base_image
  circleci/python:2.7

working_directory: &working_directory
  /home/circleci/old-ameyrupji-com

deploy_default_config: &deploy_default_config
  docker:
    - image: *deploy_base_image
  working_directory: *working_directory

jobs:
  upload-master:
    <<: *deploy_default_config
    steps:
      - checkout
      - aws-s3/copy:
          from: /home/circleci/old-ameyrupji-com/src/
          to: 's3://old.ameyrupji.com/'
          arguments: --recursive
  upload-develop:
    <<: *deploy_default_config
    steps:
      - checkout
      - aws-s3/copy:
          from: /home/circleci/old-ameyrupji-com/src/
          to: 's3://old.beta.ameyrupji.com/'
          arguments: --recursive

workflows:
  version: 2
  build-upload:
    jobs:
      - approve-master:
          type: approval
          filters:
            branches:
              only: master
      - upload-master:
          requires:
              - approve-master
          filters:
              branches:
                only: master
      - upload-develop:
          filters:
              branches:
                only: develop